// Daily Verse content — King James Version (public domain).
// t = verse text, r = reference.
window.VERSES = [
  { t: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", r: "John 3:16" },
  { t: "The LORD is my shepherd; I shall not want.", r: "Psalm 23:1" },
  { t: "I can do all things through Christ which strengtheneth me.", r: "Philippians 4:13" },
  { t: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.", r: "Jeremiah 29:11" },
  { t: "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.", r: "Proverbs 3:5-6" },
  { t: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.", r: "Romans 8:28" },
  { t: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee.", r: "Isaiah 41:10" },
  { t: "Be still, and know that I am God.", r: "Psalm 46:10" },
  { t: "Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.", r: "Joshua 1:9" },
  { t: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", r: "Matthew 6:33" },
  { t: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.", r: "Philippians 4:6" },
  { t: "This is the day which the LORD hath made; we will rejoice and be glad in it.", r: "Psalm 118:24" },
  { t: "For we walk by faith, not by sight.", r: "2 Corinthians 5:7" },
  { t: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?", r: "Psalm 27:1" },
  { t: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.", r: "1 Corinthians 13:4" },
  { t: "Now faith is the substance of things hoped for, the evidence of things not seen.", r: "Hebrews 11:1" },
  { t: "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer.", r: "Psalm 19:14" },
  { t: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.", r: "Matthew 11:28" },
  { t: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary.", r: "Isaiah 40:31" },
  { t: "And be not conformed to this world: but be ye transformed by the renewing of your mind.", r: "Romans 12:2" },
  { t: "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD, which made heaven and earth.", r: "Psalm 121:1-2" },
  { t: "Commit thy works unto the LORD, and thy thoughts shall be established.", r: "Proverbs 16:3" },
  { t: "Casting all your care upon him; for he careth for you.", r: "1 Peter 5:7" },
  { t: "Delight thyself also in the LORD; and he shall give thee the desires of thine heart.", r: "Psalm 37:4" },
  { t: "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.", r: "John 14:6" },
  { t: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.", r: "Psalm 91:1" },
  { t: "It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.", r: "Lamentations 3:22-23" },
  { t: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", r: "2 Timothy 1:7" },
  { t: "O taste and see that the LORD is good: blessed is the man that trusteth in him.", r: "Psalm 34:8" },
  { t: "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?", r: "Micah 6:8" },
  { t: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men.", r: "Colossians 3:23" },
  { t: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.", r: "Romans 15:13" },
  { t: "Create in me a clean heart, O God; and renew a right spirit within me.", r: "Psalm 51:10" },
  { t: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.", r: "Ephesians 2:8" },
  { t: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.", r: "Matthew 5:16" },
  { t: "The LORD is nigh unto all them that call upon him, to all that call upon him in truth.", r: "Psalm 145:18" },
  { t: "The name of the LORD is a strong tower: the righteous runneth into it, and is safe.", r: "Proverbs 18:10" },
  { t: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.", r: "Isaiah 26:3" },
  { t: "We love him, because he first loved us.", r: "1 John 4:19" },
  { t: "Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name.", r: "Psalm 100:4" },
  { t: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.", r: "James 1:5" },
  { t: "The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.", r: "Nahum 1:7" },
  { t: "The LORD is my strength and my shield; my heart trusted in him, and I am helped.", r: "Psalm 28:7" },
  { t: "Then spake Jesus again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.", r: "John 8:12" },
  { t: "Be strong and of a good courage, fear not, nor be afraid: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.", r: "Deuteronomy 31:6" },
  { t: "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.", r: "Psalm 16:11" },
  { t: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness.", r: "2 Corinthians 12:9" },
  { t: "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love.", r: "Zephaniah 3:17" },
  { t: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.", r: "Psalm 139:14" },

  // ---- Hindu: Bhagavad Gita shlokas (Sanskrit = public domain; Hindi meaning original) ----
  { faith: "hindu", lang: "sa", sa: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥", t: "तेरा अधिकार केवल कर्म करने में है, उसके फल में कभी नहीं। इसलिए फल की इच्छा से कर्म मत कर, और कर्म न करने में भी तेरी आसक्ति न हो।", r: "श्रीमद्भगवद्गीता 2.47" },
  { faith: "hindu", lang: "sa", sa: "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत। अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्॥", t: "हे भारत! जब-जब धर्म की हानि और अधर्म की वृद्धि होती है, तब-तब मैं स्वयं को प्रकट करता हूँ।", r: "श्रीमद्भगवद्गीता 4.7" },
  { faith: "hindu", lang: "sa", sa: "परित्राणाय साधूनां विनाशाय च दुष्कृताम्। धर्मसंस्थापनार्थाय सम्भवामि युगे युगे॥", t: "साधुओं की रक्षा, दुष्टों के विनाश और धर्म की स्थापना के लिए मैं युग-युग में प्रकट होता हूँ।", r: "श्रीमद्भगवद्गीता 4.8" },
  { faith: "hindu", lang: "sa", sa: "न जायते म्रियते वा कदाचिन्नायं भूत्वा भविता वा न भूयः। अजो नित्यः शाश्वतोऽयं पुराणो न हन्यते हन्यमाने शरीरे॥", t: "आत्मा न कभी जन्म लेती है न मरती है। यह अजन्मा, नित्य, शाश्वत और पुरातन है; शरीर के नष्ट होने पर भी इसका नाश नहीं होता।", r: "श्रीमद्भगवद्गीता 2.20" },
  { faith: "hindu", lang: "sa", sa: "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज। अहं त्वा सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः॥", t: "सब धर्मों को छोड़कर केवल मेरी शरण में आ जा। मैं तुझे सब पापों से मुक्त कर दूँगा, तू शोक मत कर।", r: "श्रीमद्भगवद्गीता 18.66" },
  { faith: "hindu", lang: "sa", sa: "उद्धरेदात्मनात्मानं नात्मानमवसादयेत्। आत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः॥", t: "मनुष्य स्वयं ही अपना उद्धार करे, स्वयं को गिराए नहीं। मनुष्य स्वयं ही अपना मित्र है और स्वयं ही अपना शत्रु है।", r: "श्रीमद्भगवद्गीता 6.5" },
  { faith: "hindu", lang: "sa", sa: "नैनं छिन्दन्ति शस्त्राणि नैनं दहति पावकः। न चैनं क्लेदयन्त्यापो न शोषयति मारुतः॥", t: "इस आत्मा को न शस्त्र काट सकते हैं, न अग्नि जला सकती है, न जल भिगो सकता है और न वायु सुखा सकती है।", r: "श्रीमद्भगवद्गीता 2.23" },
  { faith: "hindu", lang: "sa", sa: "श्रेयान्स्वधर्मो विगुणः परधर्मात्स्वनुष्ठितात्। स्वधर्मे निधनं श्रेयः परधर्मो भयावहः॥", t: "अच्छी तरह किए गए दूसरे के धर्म से, गुणरहित होने पर भी अपना धर्म श्रेष्ठ है। अपने धर्म में मरना भी कल्याणकारी है।", r: "श्रीमद्भगवद्गीता 3.35" },

  // ---- Hindu: short devotional thoughts in Hindi (original) ----
  { faith: "hindu", lang: "hi", t: "जो हुआ, अच्छा हुआ। जो हो रहा है, अच्छा हो रहा है। जो होगा, वह भी अच्छा ही होगा।", r: "विचार" },
  { faith: "hindu", lang: "hi", t: "मन को शांत रखो और ईश्वर पर पूरा भरोसा रखो — वही हर परिस्थिति में सही मार्ग दिखाते हैं।", r: "विचार" },
  { faith: "hindu", lang: "hi", t: "आज का दिन ईश्वर का दिया हुआ उपहार है। इसे प्रेम, सेवा और कृतज्ञता के साथ जियो।", r: "विचार" },
  { faith: "hindu", lang: "hi", t: "कर्म करते रहो, फल की चिंता मत करो — यही जीवन का सबसे बड़ा रहस्य है।", r: "विचार" },
  { faith: "hindu", lang: "hi", t: "जहाँ श्रद्धा और धैर्य है, वहाँ ईश्वर की कृपा अवश्य आती है।", r: "विचार" },
  { faith: "hindu", lang: "hi", t: "सुबह की पहली सोच सकारात्मक रखो — पूरा दिन उज्ज्वल होगा। शुभ प्रभात!", r: "विचार" },
  { faith: "hindu", lang: "hi", t: "क्रोध को शांति से, अहंकार को विनम्रता से और भय को विश्वास से जीतो।", r: "विचार" },
  { faith: "hindu", lang: "hi", t: "ईश्वर का नाम ही सबसे बड़ा सहारा है — हर साँस में उसे याद रखो।", r: "विचार" }
];

